// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EscolaProject.DATA.Models
{
    public partial class Aluno
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("nome_aluno")]
        [StringLength(50)]
        public string NomeAluno { get; set; }
        [Required]
        [Column("email")]
        [StringLength(10)]
        public string Email { get; set; }

        [InverseProperty("IdNavigation")]
        public virtual Notas Notas { get; set; }
    }
}