// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EscolaProject.DATA.Models
{
    public class Aluno : BaseModel
    {
        
        [Required]
        [Column("nome_aluno")]
        [StringLength(50)]
        public string NomeAluno { get; set; }
        [Required]
        [Column("email")]
        [StringLength(10)]
        public string Email { get; set; }

        [NotMapped]
        public virtual Notas Notas { get; set; }

        [NotMapped]
        public virtual List<MateriaAluno> MateriasAlunos { get; set; }

        [NotMapped]
        public virtual List<Materia> Materias { get; set; }
    }
}