// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EscolaProject.DATA.Models
{
    public class MateriaAluno : BaseModel
    {
        [Required]
        [Column("id_aluno")]
        [StringLength(50)]
        public int IdAluno { get; set; }

        [Required]
        [Column("id_materia")]
        [StringLength(10)]
        public int IdMateria { get; set; }

        [NotMapped]
        public Materia Materia { get; set; }

        [NotMapped]
        public Aluno Aluno { get; set; }

        [NotMapped]
        public virtual List<MateriaAluno> MateriasAlunos { get; set; }

    }
}