// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EscolaProject.DATA.Models
{
    public partial class Notas : BaseModel
    {
        [Column("Id_aluno")]
        public int IdAluno { get; set; }

        [Column("id_materia")]
        public int IdMateria { get; set; }

        [Column("nota")]
        public int Nota { get; set; }

        [Column("data", TypeName = "date")]
        public DateTime Data { get; set; }

        [NotMapped]
        public virtual Materia Materia { get; set; }

        [NotMapped]
        public virtual Aluno Aluno { get; set; }

        [NotMapped]
        public virtual List<Aluno> Alunos { get; set; }

        [NotMapped]
        public virtual List<Materia> Materias { get; set; }
    }
}