// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EscolaProject.DATA.Models
{
    public partial class Notas
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("Id_aluno")]
        public int IdAluno { get; set; }
        [Column("id_materia")]
        public int IdMateria { get; set; }
        [Column("nota")]
        public int Nota { get; set; }
        [Column("data", TypeName = "date")]
        public DateTime Data { get; set; }

        [ForeignKey("Id")]
        [InverseProperty("Notas")]
        public virtual Materia Id1 { get; set; }
        [ForeignKey("Id")]
        [InverseProperty("Notas")]
        public virtual Aluno IdNavigation { get; set; }
    }
}